<h2> ======================================================</h2>
 <h1>MA477 - Theory and Applications of Data Science</h1> 
  <h1>Lesson 2: Introduction to NumPy</h1> 
 
 <h4>Dr. Valmir Bucaj</h4>
 <br>
 United States Military Academy, West Point, AY20-2
<h2>=======================================================</h2>

In [3]:
import numpy as np

<h2>==================================================</h2>
<br>
<h1>HOMEWORK #1</h1>

<h2>=================================================</h2>

<h3> Complete the following exercises. Document your code as necessary.</h3>
<br>

<ol>
<li><font size=3> Create a 5 by 7 numpy array of random integers with values between 3 and 11 inclusive. Then do the following:
    <ol> <li>Check the data type of the array</li>
        <li>Find the maximum of the entire array</li>
        <li>Find the minimum value of each row</li>
        <li>Find the index where the minimum value of each row occurs</li>
    </ol></font></li>
</ol>

In [4]:
arr=np.random.randint(3,11,35)
arr_1=arr.reshape(5,7)
arr_1.dtype

dtype('int32')

In [5]:
arr_1.max()

10

In [6]:
arr_1.min(axis=1)

array([3, 5, 3, 3, 3])

In [9]:
arr_1.argmin(axis=1)

array([0, 2, 4, 1, 1], dtype=int64)

<ol start='2'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])
```    
</ol>

In [11]:
my_list2=[ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99]
arr_2=np.array(my_list2)
#Result
arr_2

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])

<ol start='3'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])
```    
</ol>

In [12]:
my_mat2=[[4,9,14,19,24],[29, 34, 39, 44, 49],[54, 59, 64, 69, 74],[79, 84, 89, 94, 99]]
mat_arr=np.array(my_mat2)
#Result
mat_arr

array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])

<ol start='4'>
   
<li> <font size='3'>Create a 4 by 2 by 3 array of normally distributed values</font></li>
   
</ol>

In [13]:
three_d_arr=np.random.randn(4,2,3)
#Result
three_d_arr

array([[[ 0.68755467,  0.76563959, -1.01684518],
        [-0.79512064, -1.07250588, -0.7882791 ]],

       [[-1.52546247,  0.23941679, -0.06602307],
        [ 1.54377922,  0.90776271, -0.67895116]],

       [[ 1.43599164,  1.22257912,  1.17507424],
        [ 0.11439446,  0.97772449, -1.07324892]],

       [[ 2.93659074,  0.01759926,  0.79465512],
        [ 0.76667296, -0.3499803 , -0.40813003]]])

<ol start='5'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array(including the correct
    data type): </font></li>

```python
#Result
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]]
```    

</ol>

In [14]:
np.eye(6,6,k=-2,dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

<ol start='6'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
```    
<ol>
    <li>Enter the code below that selects only the last four elements:</li>

```python
#Result
array([27, 29, 31, 33])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([ 3,  9, 15, 21, 27, 33])
```
</ol>
</ol>

In [15]:
my_list6=[ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33]
arr_6=np.array(my_list6)
#Result
arr_6[arr_6>26]

array([27, 29, 31, 33])

In [16]:
arr_6[arr_6%3==0]

array([ 3,  9, 15, 21, 27, 33])

<ol start='7'>
   
<li> <font size='3'>Given the 2D numpy array below </font></li>

```python
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
```    
<ol>
    <li> Enter the code below that selects the element 72 on the last row</li>
    <br>
   <li>Enter the code below that selects the following subarray:</li>

```python
#Result
array([[76,  3],
       [26, 71],
       [38, 54]])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])
```
</ol>
</ol>

In [17]:
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
arr_2d[4,5]

72

In [18]:
arr_2d[2:,3:5]


array([[76,  3],
       [26, 71],
       [38, 54]])

In [20]:
arr_2d[1:4]

array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])

<ol start='8'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
arr=np.arange(1,50,3)
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])
```    
<ol>
    <li>Enter the code that selects all elements larger than 7 and smaller than 43:

```python
#Result
array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

```
   <li>Enter the code below that selects all even integers larger than 11 and smaller than 45:</li>

```python
#Result
array([16, 22, 28, 34, 40])
```
</ol>
</ol>

In [40]:
arr_8=np.arange(1,50,3)
arr_8[(arr_8>7) & (arr_8<43)]

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

In [41]:
arr_8[(arr_8>7) & (arr_8<43) & (arr_8%2==0)]

array([10, 16, 22, 28, 34, 40])

<ol start='9'>
   
<li> <font size='3'>Create a 1D uniformly distributed array with 20 elements and compute: </font></li>


<ol>
    <li> Mean</li>

   <li>Standard Deviation</li>
   
   <li>Median</li>
   
   <li>Mean of its log values</li>
</ol>
</ol>

In [46]:
arr_9 = np.random.rand(20)
np.mean(arr_9)

0.45311720967024344

In [47]:
np.std(arr_9)

0.31910927212306917

In [48]:
np.median(arr_9)

0.482118468841707

In [51]:
arr_9log = np.log(arr_9)
np.mean(arr_9log)

-1.2897637035683318

<ol start='10'>
   
<li> <font size='3'>Write a function that:</font></li>
    <ol>
    <br>
   <li> takes a 1D Numpy array as input and prints out the <b>reversed</b> array with element type float</li>

For example, if you input the following array into your function
```python
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])
```
your function should print out

```python
array([23., 21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.,  1.])
```

<li> takes a 2D Numpy array as input and prints out a copy of the input array <b> flattened</b> to one dimension</li>

For example if the input array is:
```python
array([[7, 4, 8, 3],
       [6, 3, 4, 3],
       [4, 7, 5, 4]])
```
the output of your function should be
```python
array([7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4])
```
</ol>
</ol>

In [65]:
arr_10a = np.arange(10)
arr_10a_flip = np.flip(arr_10a)
arr_10a_flip.astype(float)

array([9., 8., 7., 6., 5., 4., 3., 2., 1., 0.])

In [68]:
arr_10b = np.random.randint(2,7,size=(3,5))
arr_10b.flatten()

array([3, 5, 2, 2, 6, 3, 5, 6, 6, 5, 4, 2, 4, 6, 6])